### ISSUE TITLE
add activity form

### ISSUE THREAD

**Issue by itamarjo** [dortheimer/CitizensForCities#8]
Activity should have the following fields:
1. name,
2. address.
3. description.
4. admin.

**Comment by dortheimer** [comment]
It should have:
headline
description
address (Validate with geocoder)
status (From a predefined list)
Some categories (Selecting from a predefined list) 

User must be logged in

**Comment by itamarjo** [comment]
Thanks for the comments, 
I see that currently the back doesn't support status, and categories. 
Should we add it? Also, do we want the page to load the list of status and categories, or maybe for first stage we will add it manually? what do you think?

**Comment by annlillman** [comment]
![desktop hd copy](https://user-images.githubusercontent.com/29868046/30062359-8e43dd5e-9253-11e7-99bd-da068ac0a66b.png)
![desktop hd](https://user-images.githubusercontent.com/29868046/30062360-8e671a80-9253-11e7-8925-b08bd7dd7bdd.png)
